### ISSUE TITLE
Update table styling for small devices

### ISSUE THREAD

**Issue by siamdakiang** [Dynatrace/css-groundhog#100]
tables on small devices should look like here https://dev-jira.dynatrace.org/browse/UX-5103

**Comment by ddprrt** [comment]
http://codepen.io/ddprrt/pen/NdgJVY
https://css-tricks.com/responsive-data-tables/

**Comment by katrin-freihofner** [comment]
Fixed by [103](https://github.com/Dynatrace/css-groundhog/pull/103)
