### ISSUE TITLE
.is-expandable vs. is-active

### ISSUE THREAD

**Issue by katrin-freihofner** [Dynatrace/css-groundhog#119]
Rethink the differences and usage of these classes (expandable in content vs. sidemenu)

**Comment by katrin-freihofner** [comment]
https://dev-jira.dynatrace.org/browse/UX-5523

**Comment by ddprrt** [comment]
There are two hard problems in computer science
1. cache invalidation
2. naming things
3. off by one  errors

Problem: is-expanded is to specific, is-active is already used. Maybe make is-expanded to is-active, and find a good, good name for is-active (is-current, is-highlighted, is-mawurscht)

**Comment by lara-aigmueller** [comment]
Fixed by: https://github.com/Dynatrace/css-groundhog/pull/146
