### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by ddprrt** [Dynatrace/css-groundhog#12]
- [x] How to install Groundhog
- [x] Performance tips

Components: 
- [x] Breadcrumbs
- [x] Button
- [x] Checkbox
- [x] Expandable
- [x] Footer
- [x] Header
- [x] Icons
- [x] Navbar
- [x] Pagination
- [x] Radiobutton
- [x] Sidebar
- [x] Slider
- [x] Switch
- [x] Table
- [x] Tabs
- [x] Tags
- [x] Textarea
- [x] Tile

**Comment by katrin-freihofner** [comment]
will be fixed with v0.9.0
