### ISSUE TITLE
Checkbox ticks placed incorrectly

### ISSUE THREAD

**Issue by DerGernTod** [Dynatrace/css-groundhog#141]
check out http://groundhog.dynalabs.io/doc/components/checkbox/ with the latest firefox (i got 54.0a2)

when i tick a checkbox, the tick and the box are misplaced:
![grafik](https://cloud.githubusercontent.com/assets/19726130/26638966/d845017a-4623-11e7-8c48-66c9d410d2b9.png)

similarly, the checks of the first two checkboxes are not in the center of the box:
![grafik](https://cloud.githubusercontent.com/assets/19726130/26639012/f76d2546-4623-11e7-9e25-dd12c2e2c4eb.png)

**Comment by tomheller** [comment]
thank you @DerGernTod, we will take care of this as soon as we can. We're at a conference tomorrow, but will definitely find time during next week to fix this.

**Comment by katrin-freihofner** [comment]
@DerGernTod: fixed by https://github.com/Dynatrace/css-groundhog/pull/144

**Comment by tomheller** [comment]
@DerGernTod the checkbox bug should be solved in groundhog version v0.7.0 
Please let us know if there are any more problems
