### ISSUE TITLE
Manually generate changelog

### ISSUE THREAD

**Issue by tomheller** [Dynatrace/css-groundhog#175]
The automation is bugged and broken. It seems it would be simpler to manually maintain the changelog from now on, since there are too many weird differences and version conflicts going on. 

@lara-aigmueller if you like, could you migrate the current changelog to a manually maintained one, 
meaning: 
* clean out overly coplicated commit messages
* remove the changelog task from `gulpfile.js`
* remove changelog.md from gitignore

It would also be great to have this for v2 if possible.

**Comment by lara-aigmueller** [comment]
Fixed by: https://github.com/Dynatrace/css-groundhog/pull/177
