### ISSUE TITLE
New nav: alignment is weird

### ISSUE THREAD

**Issue by ddprrt** [Dynatrace/css-groundhog#187]
logo and secondary are not aligned
CTA and nav point are not aligned
secondary and breadcrumb are not aligned.

**Comment by tomheller** [comment]
![alignments](https://user-images.githubusercontent.com/6338434/29018917-340b672e-7b5d-11e7-83ad-9bffcb1b95a5.png)
Alignments of edges is off.

**Comment by ddprrt** [comment]
![screen shot 2017-08-07 at 10 52 14](https://user-images.githubusercontent.com/1374451/29019422-adde0cc2-7b5e-11e7-9c28-d36422cc8cde.png)
Even more examples. It's very visible on the left.
