### ISSUE TITLE
Unable to get Dynatrace widget library resources

### ISSUE THREAD

**Issue by RoyinRolland** [Dynatrace/css-groundhog#206]
https://bitbucket.lab.dynatrace.org/projects/LIB/repos/widget-library/browse not found

**Comment by tomheller** [comment]
Hey @RoyinRolland, can you specify the issue. Is bitbucket linked in the library somewhere?

**Comment by RoyinRolland** [comment]
README.md

**Comment by tomheller** [comment]
This is an internal resource for the dynatrace company and not for public use. Sorry about that.

**Comment by RoyinRolland** [comment]
👌 thank you

**Comment by RoyinRolland** [comment]
Whether it is open source later?

**Comment by tomheller** [comment]
I'm sorry no. the Widget library repository will not be open source anytime soon. Additionally I'm not entirely certain it is something you would want to use, since it is a java implementation of the components described in groundhog.
