### ISSUE TITLE
Expandable Table

### ISSUE THREAD

**Issue by tomheller** [Dynatrace/css-groundhog#39]
Like this: 
http://assets.ruxitlabs.com/styleguides/tables/#expandable-tables-in-content-pages

Maybe this can be combined with https://github.com/Dynatrace/css-groundhog/tree/master/src/expandable

**Comment by lara-aigmueller** [comment]
Zero or more tbody elements are allowed in a table https://www.w3.org/TR/html5/tabular-data.html#the-table-element

**Comment by ddprrt** [comment]
Fixed by #42
