### ISSUE TITLE
Loading distractor

### ISSUE THREAD

**Issue by ddprrt** [Dynatrace/css-groundhog#5]

**Comment by tomheller** [comment]
It would still be great to have a single element solution for this one. Are we open to do this with custom elements, svg? or some alternative technology as long as it doesn't create a massive dependency.

**Comment by ddprrt** [comment]
YESSSSSSSS
![](https://media.giphy.com/media/S3Ot3hZ5bcy8o/giphy.gif)

**Comment by katrin-freihofner** [comment]
This is done
