### ISSUE TITLE
Add steps to typography

### ISSUE THREAD

**Issue by lara-aigmueller** [Dynatrace/css-groundhog#70]
It's like an OL but applicable to all the elements

(Q: Typography? Component?)

**Comment by ddprrt** [comment]
1. Create styling for OL
2. Add classes to apply the same styling to any element

**Comment by lara-aigmueller** [comment]
Fixed by https://github.com/Dynatrace/css-groundhog/pull/147 and https://github.com/Dynatrace/css-groundhog/pull/148
