### ISSUE TITLE
Dropdowns Selectable Components

### ISSUE THREAD

**Issue by garciaba** [Dynatrace/css-groundhog#79]
Is there any dropdown component available? Something like this:

![bootstrap-select_1](https://cloud.githubusercontent.com/assets/11162075/20230341/753f8ec6-a829-11e6-91d3-36832d77e6d9.png)

**Comment by tomheller** [comment]
Hey @garciaba, there is one planned for v1 in #10, but  unfortunately we can't really say when we are going to get to it.

**Comment by tomheller** [comment]
@garciaba, @katrin-freihofner has created the select component a while back in #91. It should be available now. 
Let us know if you have any troubles.
