### ISSUE TITLE
Add Groundhog to NPM

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/css-groundhog#90]
It would be very handy if you could publish Groundhog to NPM.

**Comment by tomheller** [comment]
We are currently working on creating a release package on github, so you can npm install directly from a github endpoint. Would this also work for you, or would you prefer npm?

**Comment by beeme1mr** [comment]
We can make a GitHub release work but NPM would be preferred.

**Comment by tomheller** [comment]
I will talk to @ddprrt tomorrow to see what we can do.
