### ISSUE TITLE
Expandable documentation is missing

### ISSUE THREAD

**Issue by beeme1mr** [Dynatrace/css-groundhog#95]
The links for the expandable section at the bottom of this page doesn't exist.

http://groundhog.dynalabs.io/doc/components/sidebar/

**Comment by tomheller** [comment]
@beeme1mr, thank you for noticing. Unfortunately, it seems a typo snuck into the link there. It should be fix has be http://groundhog.dynalabs.io/doc/components/expandable/

the fix has been submitted and will be out with the next deployment.
