### ISSUE TITLE
DL - DT - DD

### ISSUE THREAD

**Issue by ddprrt** [Dynatrace/css-groundhog#99]
Definition lists should look like http://assets.ruxitlabs.com/styleguides/meta_data/, but should work with both long and short defs.

**Comment by ddprrt** [comment]
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/dl

**Comment by lara-aigmueller** [comment]
Fixed by https://github.com/Dynatrace/css-groundhog/pull/106 and https://github.com/Dynatrace/css-groundhog/pull/148
